name: 'Rust Unit Tests'
description: 'Executes Rust unit tests'
inputs:
  target:
    description: 'Specific target triplet.'
    required: false
    default: ''
  sanitizer:
    description: 'Sanitizer to use for test.'
    required: false
    default: ''
  results-xml:
    description: 'Output unit tests results XML filename.'
    required: false
    default: 'unit-tests-results.xml'
  enable-coverage:
    description: 'Enable code coverage.'
    required: false
    default: 'false'
  upload-results:
    description: 'Upload unit test results as a GitHub check.'
    required: false
    default: 'true'
  check-name:
    description: 'GitHub check name for published test results.'
    required: false
    default: 'Unit Tests Results'
  cargo-test-command:
    description: 'Cargo test command or alias to run (e.g., test, test-slang).'
    required: false
    default: 'test'


runs:
  using: "composite"
  steps:
    - name: Install build target
      if: inputs.target != '' && runner.os != 'Windows'
      uses: ./.github/actions/setup-rust
      with:
        target: ${{ inputs.target }}

    - name: Define build target
      id: build-target
      if: inputs.target != ''
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: echo "target=--target ${{ inputs.target }}" >> "${GITHUB_OUTPUT}"

    - name: Fetch dependencies
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cargo fetch --locked

    - name: Prepare test env
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: |
        cargo install cargo2junit --locked
        if [ '${{ inputs.enable-coverage }}' = 'true' ]; then
          cargo install cargo-llvm-cov --locked
        fi

    - name: Run unit tests (release)
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash -ex {0}' }}
      env:
        RUSTC_BOOTSTRAP: 1
      if: inputs.sanitizer == ''
      run: |
        TEST_COMMAND="${{ inputs.cargo-test-command }}"
        if [ '${{ inputs.enable-coverage }}' = 'true' ]; then
          export LLVM_COV=$(which llvm-cov)
          export LLVM_PROFDATA=$(which llvm-profdata)
          TEST_COMMAND="llvm-cov --all-features --workspace --lcov --output-path lcov.info"
        fi
        # Use LLD on Windows to properly link with libstdc++.
        if [[ ${RUNNER_OS} = Windows ]] || [[ ${RUNNER_OS} = Linux ]]; then
          export RUSTFLAGS="${RUSTFLAGS} -C link-arg=-fuse-ld=lld"
        fi
        if [ "${TEST_COMMAND}" = "test" ]; then cargo build --frozen; fi
        cargo ${TEST_COMMAND} --frozen --release ${{ steps.build-target.outputs.target }} -- -Z unstable-options \
          --format json | tee -a release-results.json | grep 'failed'
        if [ $? -eq 0 ]; then
          cargo2junit < release-results.json > "release-${{ inputs.results-xml }}"
        fi

    - name: Install sanitizer components
      if: inputs.sanitizer != '' && runner.os != 'Windows'
      uses: ./.github/actions/setup-rust
      with:
        components: rust-src

    - name: Run unit tests (debug)
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash -ex {0}' }}
      env:
        RUSTC_BOOTSTRAP: 1
      run: |
        if [ '${{ inputs.sanitizer }}' != '' ]; then
          export ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer)
        fi
        # Use LLD on Windows and Linux to properly link with libstdc++.
        # On Windows, also strip debuginfo: PE/COFF has a 2 GB SizeOfImage limit
        # and debug binaries statically linking LLVM+MLIR+LLD can exceed it,
        # producing "%1 is not a valid Win32 application" (os error 193).
        # Skip when using sanitizers — clang needs its native linker for ASan runtime.
        if [[ ${RUNNER_OS} = Windows ]]; then
          export RUSTFLAGS="${RUSTFLAGS} -C link-arg=-fuse-ld=lld -C strip=debuginfo"
        elif [[ ${RUNNER_OS} = Linux && '${{ inputs.sanitizer }}' = '' ]]; then
          export RUSTFLAGS="${RUSTFLAGS} -C link-arg=-fuse-ld=lld"
        fi
        # Set sanitizer flags per-target to avoid breaking proc-macro builds.
        # -Z sanitizer=address instruments Rust code AND links Rust's bundled
        # ASan runtime (librustc-stable_rt.asan.a). Do NOT also pass
        # -C link-arg=-fsanitize=address — that causes clang to inject a second
        # ASan runtime (libclang_rt.asan), producing duplicate symbol errors.
        if [ '${{ inputs.sanitizer }}' != '' ]; then
          if [ '${{ inputs.target }}' = '' ]; then
            echo "::error::Sanitizer requires an explicit target"
            exit 1
          fi
          TARGET_UPPER=$(echo "${{ inputs.target }}" | tr '[:lower:]-' '[:upper:]_')
          SAN='${{ inputs.sanitizer }}'
          export "CARGO_TARGET_${TARGET_UPPER}_RUSTFLAGS=${RUSTFLAGS} -Z sanitizer=${SAN}"
          export "CARGO_TARGET_${TARGET_UPPER}_LINKER=clang"
        fi
        if [ '${{ inputs.target }}' != '' ]; then
          export CARGO_BIN_EXE_SOLX="./target/${{ inputs.target }}/debug/solx"
        fi
        if [ "${{ inputs.cargo-test-command }}" = "test" ]; then cargo build --frozen ${{ steps.build-target.outputs.target }}; fi
        cargo ${{ inputs.cargo-test-command }} --frozen ${{ steps.build-target.outputs.target }} -- -Z unstable-options \
          --format json | tee -a debug-results.json | grep 'failed'
        if [ $? -eq 0 ]; then
          cargo2junit < debug-results.json > "debug-${{ inputs.results-xml }}"
        fi

    - name: Upload results Linux
      if: (success() || failure()) && runner.os == 'Linux' && inputs.upload-results == 'true'
      uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
      with:
        check_name: ${{ runner.os }} ${{ runner.arch }} ${{ inputs.check-name }}
        files: '*${{ inputs.results-xml }}'
        action_fail_on_inconclusive: true
        comment_mode: off

    - name: Upload test results MacOS
      if: (success() || failure()) && runner.os == 'macOS' && inputs.upload-results == 'true'
      uses: EnricoMi/publish-unit-test-result-action/macos@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
      with:
        check_name: ${{ runner.os }} ${{ runner.arch }} ${{ inputs.check-name }}
        files: '*${{ inputs.results-xml }}'
        action_fail_on_inconclusive: true
        comment_mode: off

    - name: Upload test results Windows
      if: (success() || failure()) && runner.os == 'Windows' && inputs.upload-results == 'true'
      uses: EnricoMi/publish-unit-test-result-action/windows@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
      with:
        check_name: ${{ runner.os }} ${{ runner.arch }} ${{ inputs.check-name }}
        files: '*${{ inputs.results-xml }}'
        action_fail_on_inconclusive: true
        comment_mode: off
