name: 'Build'
description: 'Build Rust executable.'
inputs:
  exec_name:
    description: 'Name of the executable.'
    required: true
  target:
    description: 'Specific build target triplet.'
    required: false
    default: ''
  sanitizer:
    description: 'Sanitizer to use for build.'
    required: false
    default: ''
  release-suffix:
    description: 'Suffix to use for release name.'
    required: false
    default: ''
  build-type:
    description: 'Type of build: release or debug.'
    required: false
    default: 'release'
  enable-coverage:
    description: 'Enable code coverage.'
    required: false
    default: 'false'

outputs:
  binary-path:
    description: 'Path to the built binary.'
    value: ${{ steps.build.outputs.binary-path }}

runs:
  using: "composite"
  steps:
    - name: Install build target
      if: inputs.target != '' && runner.os != 'Windows'
      uses: ./.github/actions/setup-rust
      with:
        target: ${{ inputs.target }}

    - name: Define build target
      id: build-target
      if: inputs.target != ''
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: echo "target=--target ${{ inputs.target }}" >> $GITHUB_OUTPUT

    - name: Install sanitizer components
      if: inputs.sanitizer != '' && runner.os != 'Windows'
      uses: ./.github/actions/setup-rust
      with:
        components: rust-src

    - name: Build
      id: build
      env:
        RUSTC_BOOTSTRAP: 1
        RUSTFLAGS: '-C target-feature=+crt-static'
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash -ex {0}' }}
      run: |
        # Sanitize build environment: clear variables that could tamper with compilation.
        # RUSTC_WRAPPER: could redirect compilation through a malicious wrapper.
        # LD_PRELOAD / DYLD_*: could inject code into compiler and linker processes.
        # LLVM_SYS_* / MLIR_SYS_* / TABLEGEN_*: could redirect to a trojaned LLVM
        #   (safe defaults from .cargo/config.toml will be used instead).
        unset RUSTC_WRAPPER LD_PRELOAD \
          DYLD_INSERT_LIBRARIES DYLD_LIBRARY_PATH DYLD_FRAMEWORK_PATH \
          DYLD_FALLBACK_LIBRARY_PATH DYLD_FALLBACK_FRAMEWORK_PATH \
          2>/dev/null || true
        for var in $(env | grep -oE '^(LLVM_SYS|MLIR_SYS|TABLEGEN)_[^=]*'); do unset "$var"; done
        cargo fetch --locked
        if [ '${{ inputs.sanitizer }}' != '' ]; then
          export RUSTFLAGS="-Z sanitizer=${{ inputs.sanitizer }}"
          BUILD_STD_LIB='-Zbuild-std'
        fi
        [ ${{ inputs.build-type }} = 'release' ] && RELEASE="--release"
        if [ '${{ inputs.enable-coverage }}' = 'true' ]; then
          export RUSTFLAGS="${RUSTFLAGS} -C instrument-coverage"
        fi
        if [[ "${RUNNER_OS}" == "Windows" ]] || [[ "${RUNNER_OS}" == "Linux" ]]; then
          export RUSTFLAGS="${RUSTFLAGS} -C link-arg=-fuse-ld=lld"
        fi
        cargo ${BUILD_STD_LIB} build --frozen ${RELEASE} ${{ steps.build-target.outputs.target }}
        if [ '${{ inputs.target }}' != '' ]; then
          BINARY_DIR="${PWD}/target/${{ inputs.target }}/${{ inputs.build-type }}"
        else
          BINARY_DIR="${PWD}/target/${{ inputs.build-type }}"
        fi
        [ "$RUNNER_OS" = "Windows" ] && WIN_SUFFIX=".exe"
        echo "${BINARY_DIR}" >> "${GITHUB_PATH}"
        echo "binary-path=${BINARY_DIR}/${{ inputs.exec_name }}${WIN_SUFFIX}" >> "${GITHUB_OUTPUT}"

    - name: Prepare binary
      if: inputs.release-suffix != ''
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: |
        mkdir -p ./releases/${{ inputs.release-suffix }}
        [ "$RUNNER_OS" = "Windows" ] && WIN_SUFFIX=".exe"
        strip "./target/${{ inputs.target }}/${{ inputs.build-type }}/${{ inputs.exec_name }}${WIN_SUFFIX}"
        mv "./target/${{ inputs.target }}/${{ inputs.build-type }}/${{ inputs.exec_name }}${WIN_SUFFIX}" \
          "./releases/${{ inputs.release-suffix }}/${{ inputs.exec_name }}-${{ inputs.release-suffix }}${WIN_SUFFIX}"

    - name: Upload binary
      if: inputs.release-suffix != ''
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: release-${{ inputs.release-suffix }}
        path: releases
