name: 'Build'
description: 'Build Rust executable.'
inputs:
  exec_name:
    description: 'Name of the executable.'
    required: true
  target:
    description: 'Specific build target triplet.'
    required: false
    default: ''
  sanitizer:
    description: 'Sanitizer to use for build.'
    required: false
    default: ''
  release-suffix:
    description: 'Suffix to use for release name.'
    required: false
    default: ''
  build-type:
    description: 'Type of build: release or debug.'
    required: false
    default: 'release'
  enable-coverage:
    description: 'Enable code coverage.'
    required: false
    default: 'false'
  enable-cache:
    description: 'Enable Rust dependency caching.'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Define build environment
      id: build-env
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: |
        if [ -n "${{ inputs.target }}" ]; then
          rustup target add ${{ inputs.target }}
          echo "cargo-target=--target ${{ inputs.target }}" >> $GITHUB_OUTPUT
        fi
        TARGET_DIR="${CARGO_TARGET_DIR:-${PWD}/target}"
        if [ -n "${{ inputs.target }}" ]; then
          TARGET_PATH="${TARGET_DIR}/${{ inputs.target }}"
        else
          TARGET_PATH="${TARGET_DIR}"
        fi
        echo "target-path=${TARGET_PATH}" >> $GITHUB_OUTPUT

    - name: Rust cache
      if: inputs.enable-cache == 'true'
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "rust-cargo-cache-${{ runner.os }}-${{ runner.arch }}"
        save-if: ${{ github.ref == 'refs/heads/main' }}

    - name: Build
      env:
        RUSTC_BOOTSTRAP: 1
        RUSTFLAGS: '-C target-feature=+crt-static'
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash -ex {0}' }}
      run: |
        if [ '${{ inputs.sanitizer }}' != '' ]; then
          rustup component add rust-src --toolchain "$(rustc --version | cut -d ' ' -f2)-${TARGET}"
          export RUSTFLAGS="-Z sanitizer=${{ inputs.sanitizer }}"
          BUILD_STD_LIB='-Zbuild-std'
        fi
        [ ${{ inputs.build-type }} = 'release' ] && RELEASE="--release"
        if [ '${{ inputs.enable-coverage }}' = 'true' ]; then
          export RUSTFLAGS="${RUSTFLAGS} -C instrument-coverage"
        fi
        if [[ "${RUNNER_OS}" == "Windows" ]] || [[ "${RUNNER_OS}" == "Linux" ]]; then
          export RUSTFLAGS="${RUSTFLAGS} -C link-arg=-fuse-ld=lld"
        fi
        cargo ${BUILD_STD_LIB} build ${RELEASE} ${{ steps.build-env.outputs.cargo-target }}
        echo "${{ steps.build-env.outputs.target-path }}/${{ inputs.build-type }}" >> "${GITHUB_PATH}"

    - name: Prepare binary
      if: inputs.release-suffix != ''
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        TARGET_PATH: ${{ steps.build-env.outputs.target-path }}
      run: |
        mkdir -p ./releases/${{ inputs.release-suffix }}
        [ "$RUNNER_OS" = "Windows" ] && WIN_SUFFIX=".exe"
        BINARY="${TARGET_PATH}/${{ inputs.build-type }}/${{ inputs.exec_name }}${WIN_SUFFIX}"
        strip "${BINARY}"
        mv "${BINARY}" "./releases/${{ inputs.release-suffix }}/${{ inputs.exec_name }}-${{ inputs.release-suffix }}${WIN_SUFFIX}"

    - name: Upload binary
      if: inputs.release-suffix != ''
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ inputs.release-suffix }}
        path: releases
