# Shared action to build solx-dev with revision tracking.
# Used by build-llvm and build-solc actions.

name: 'Build solx-dev'
description: 'Builds solx-dev binary with revision-based caching.'
inputs:
  working-dir:
    description: 'Working directory containing the Cargo project.'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Build solx-dev
      working-directory: ${{ inputs.working-dir }}
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: |
        set -e
        TARGET_DIR="${CARGO_TARGET_DIR:-./target}"
        REV_FILE="${TARGET_DIR}/.solx-dev-revision"
        CURRENT_REV="$(git rev-parse HEAD 2>/dev/null || true)"
        if [ -x "${TARGET_DIR}/release/solx-dev" ] || [ -x "${TARGET_DIR}/release/solx-dev.exe" ]; then
          if [ -n "${CURRENT_REV}" ] && [ -f "${REV_FILE}" ] && [ "$(cat "${REV_FILE}")" = "${CURRENT_REV}" ]; then
            echo "solx-dev already built for ${CURRENT_REV}; skipping."
            exit 0
          fi
        fi
        cargo build --release --bin solx-dev
        if [ -n "${CURRENT_REV}" ]; then
          echo "${CURRENT_REV}" > "${REV_FILE}"
        fi
