# The general action to build the solx LLVM framework.
# It is universal for all platforms: Linux, MacOS and Windows.

name: 'Build LLVM'
description: 'Builds backend LLVM framework'
inputs:
  working-dir:
    description: 'Working directory.'
    required: false
    default: '.'
  enable-tests:
    description: "Enable tests."
    required: false
    default: 'false'
  enable-assertions:
    description: "Enable assertions."
    required: false
    default: 'true'
  enable-coverage:
    description: "Enable coverage."
    required: false
    default: 'false'
  llvm-projects:
    description: "LLVM projects to build. Sets up LLVM_ENABLE_PROJECTS variable."
    required: false
    default: ''
  sanitizer:
    description: 'A sanitizer to build LLVM with. Possible values are Address, Memory, MemoryWithOrigins, Undefined, Thread, DataFlow, and Address;Undefined'
    required: false
    default: ''
  enable-valgrind:
    description: 'Enable Valgrind for LLVM regression tests.'
    required: false
    default: 'false'
  valgrind-options:
    description: 'Space-separated list of additional valgrind options for LLVM regression tests.'
    required: false
    default: ''
  enable-rtti:
    description: 'Enable RTTI for LLVM. Required when building with MLIR.'
    required: false
    default: 'false'
  build-type:
    description: 'LLVM build type. Possible values are `Debug`, `Release`, `RelWithDebInfo`, or `MinSizeRel`. [default: Release]'
    required: false
    default: 'Release'

runs:
  using: "composite"
  steps:

    # Ninja build tool is not available on MacOS x64 runners by default. See:
    # https://github.com/actions/runner-images/issues/514
    - name: Install Ninja on MacOS x64
      if: runner.os == 'macOS' && runner.arch == 'X64'
      shell: 'bash'
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja

    - name: Install LLVM builder
      working-directory: ${{ inputs.working-dir }}
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cargo build --release --bin solx-dev

    - name: Define ccache key
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      id: ccache-key
      run: |
        KEY="llvm-${{ runner.os }}-${{ runner.arch }}"
        [ '${{ inputs.build-type }}' != 'Release' ] && KEY="${KEY}-${{ inputs.build-type }}"
        [ '${{ inputs.enable-coverage }}' = 'true' ] && KEY="${KEY}-coverage"
        [ -n '${{ inputs.llvm-projects }}' ] && KEY="${KEY}-$(echo '${{ inputs.llvm-projects }}' | tr ' ' '-')"
        [ -n '${{ inputs.sanitizer }}' ] && KEY="${KEY}-${{ inputs.sanitizer }}"
        echo "key=${KEY}" | tee -a "${GITHUB_OUTPUT}"

    # CCache action requires `apt update` on Linux Docker jobs
    - name: Prepare ccache installation
      if: runner.os == 'Linux'
      shell: 'bash'
      run: apt update

    - name: Set up compiler cache
      uses: hendrikmuhs/ccache-action@a1209f81afb8c005c13b4296c32e363431bffea5
      env:
        CCACHE_DIR: ${{ runner.temp }}/ccache-llvm
        CCACHE_BASEDIR: ${{ github.workspace }}
        CCACHE_NOHASHDIR: "true"
        CCACHE_COMPILERCHECK: "content"
      with:
        key: ${{ steps.ccache-key.outputs.key }}
        restore-keys: ${{ steps.ccache-key.outputs.key }}
        append-timestamp: true
        max-size: "2G"
        verbose: 2
        save: ${{ github.event_name != 'pull_request' }}

    - name: Build LLVM
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      working-directory: ${{ inputs.working-dir }}
      env:
        VERBOSE: 1
        CCACHE_DIR: ${{ runner.temp }}/ccache-llvm
        CCACHE_BASEDIR: ${{ github.workspace }}
        CCACHE_NOHASHDIR: "true"
        CCACHE_COMPILERCHECK: "content"
        LIBSTDCPP_SOURCE_PATH: "${{ runner.temp }}/msys64/mingw64/lib/libstdc++.a"
      run: |
        set -x
        [ "${{ inputs.enable-tests }}" = "true" ] && ENABLE_TESTS="--enable-tests"
        [ "${{ inputs.enable-assertions }}" = "true" ] && ENABLE_ASSERTIONS="--enable-assertions"
        [ "${{ inputs.enable-coverage }}" = "true" ] && ENABLE_COVERAGE="--enable-coverage"
        [ "${{ inputs.llvm-projects }}" != "" ] && LLVM_PROJECTS="--llvm-projects ${{ inputs.llvm-projects }}"
        [ "${{ inputs.enable-rtti }}" = "true" ] && ENABLE_RTTI="--enable-rtti"
        [ "${{ inputs.sanitizer }}" != "" ] && SANITIZER="--sanitizer ${{ inputs.sanitizer }}"
        if [ "${{ inputs.enable-valgrind }}" = "true" ]; then
          ENABLE_VALGRIND="--enable-valgrind"
          if [ "${{ inputs.valgrind-options }}" != "" ]; then
            VALGRIND_OPTIONS=$(printf -- "--valgrind-options=%s " ${{ inputs.valgrind-options }})
          fi
        fi

        ./target/release/solx-dev llvm build --build-type ${{ inputs.build-type }} \
          --ccache-variant=ccache ${ENABLE_TESTS} ${ENABLE_VALGRIND} ${VALGRIND_OPTIONS} ${ENABLE_ASSERTIONS} ${ENABLE_COVERAGE} ${LLVM_PROJECTS} ${ENABLE_RTTI} ${SANITIZER}

    - name: Show ccache stats
      if: always()
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        CCACHE_DIR: ${{ runner.temp }}/ccache-llvm
      run: ccache --show-stats
