[build]
rustflags = [
    "-W", "missing_docs",
]
incremental = true

[tools.clippy]
warn = [
    "missing_docs_in_private_items",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-W", "missing_docs",
    "-C", "link-arg=-mmacosx-version-min=11.0",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-W", "missing_docs",
    "-C", "link-arg=-mmacosx-version-min=11.0",
]

[profile.release]
strip = true

[env]
SOLC_PREFIX = { value = "./solx-solidity/build/", relative = true, force = true }
BOOST_PREFIX = { value = "./solx-solidity/boost/lib/", relative = true, force = true }

LLVM_SYS_211_PREFIX = { value = "./target-llvm/target-final/", relative = true, force = true }
MLIR_SYS_210_PREFIX = { value = "./target-llvm/target-final/", relative = true, force = true }
TABLEGEN_210_PREFIX = { value = "./target-llvm/target-final/", relative = true, force = true }

[alias]
run-tester = "run --bin solx-tester -- --solidity-compiler ./target/release/solx"

clippy-slang = "clippy -p solx-slang -p solx-mlir -p solx --no-default-features --features slang --target-dir target-slang"
build-slang = "build -p solx-slang -p solx-mlir -p solx --no-default-features --features slang --target-dir target-slang"
test-slang = "test -p solx-slang -p solx-mlir -p solx --no-default-features --features slang --target-dir target-slang"
run-tester-slang = "run --bin solx-tester --no-default-features --features slang-ast --target-dir target-slang -- --solidity-compiler ./target-slang/release/solx -O M3B3"
