[build]
rustflags = [
    "-W", "missing_docs",
]
incremental = true

[target.x86_64-apple-darwin]
rustflags = [
    "-W", "missing_docs",
    "-C", "link-arg=-mmacosx-version-min=11.0",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-W", "missing_docs",
    "-C", "link-arg=-mmacosx-version-min=11.0",
]

[profile.release]
strip = true

[env]
LLVM_SYS_211_PREFIX = { value = "./target-llvm/target-final/", relative = true, force = true }
MLIR_SYS_210_PREFIX = { value = "./target-llvm/target-final/", relative = true, force = true }
TABLEGEN_210_PREFIX = { value = "./target-llvm/target-final/", relative = true }

[alias]
run-tester = "run --bin solx-tester -- --solidity-compiler ./target/release/solx -O M3B3"
