name: 'Cargo check'
description: 'Checks cargo with check, deny, format, clippy and udeps.'

runs:
  using: composite
  steps:

    - name: Install rustc nightly
      uses: ./.github/actions/setup-rust
      with:
        toolchain: nightly

    - name: Cargo deny
      uses: EmbarkStudios/cargo-deny-action@3fd3802e88374d3fe9159b834c7714ec57d6c979 # v2
      with:
        command-arguments: "--allow unmaintained --hide-inclusion-graph"

    - name: Fetch dependencies
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cargo fetch --locked

    - name: Cargo check
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cargo check --frozen --verbose

    - name: Cargo format
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cargo fmt --all -- --check --verbose

    - name: Cargo clippy
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cargo clippy --frozen

    - name: Cargo udeps
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: |
        cargo install cargo-udeps --locked
        cargo +nightly udeps --frozen --all-targets

