# The general action to build solc.
# It is universal for all platforms: Linux, macOS and Windows.
# Build logic is implemented in solx-dev Rust tool.

name: 'Build solc'
description: 'Builds solc executable.'
inputs:
  working-dir:
    description: 'Working directory containing solx-solidity submodule.'
    required: false
    default: 'solx-solidity'
  cmake-build-type:
    description: 'CMake build type (Release, Debug, or RelWithDebInfo).'
    required: false
    default: 'Release'
  boost-version:
    description: 'Boost version.'
    required: false
    default: '1.83.0'
runs:
  using: "composite"
  steps:

    - name: Build solx-dev
      # Run from the checkout root that owns solx-solidity
      working-directory: ${{ inputs.working-dir }}/..
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cargo fetch --locked && cargo build --frozen --release --bin solx-dev

    # CCache action requires `apt update` on Linux Docker jobs
    - name: Prepare ccache installation
      if: runner.os == 'Linux'
      shell: 'bash'
      run: apt update

    - name: Set up compiler cache for solc
      uses: hendrikmuhs/ccache-action@a1209f81afb8c005c13b4296c32e363431bffea5
      env:
        CCACHE_DIR: ${{ runner.temp }}/ccache-solc
        CCACHE_BASEDIR: ${{ github.workspace }}
        CCACHE_NOHASHDIR: "true"
        CCACHE_COMPILERCHECK: "content"
      with:
        key: solc-${{ runner.os }}-${{ runner.arch }}
        restore-keys: solc-${{ runner.os }}-${{ runner.arch }}
        append-timestamp: true
        max-size: "2G"
        verbose: 2
        save: ${{ github.event_name != 'pull_request' }}

    - name: Restore Boost cache
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ${{ inputs.working-dir }}/boost
        key: v1-boost-${{ inputs.boost-version }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('solx-dev/src/solc/boost.rs') }}

    - name: Build solc
      # Run from the checkout root that owns solx-solidity
      working-directory: ${{ inputs.working-dir }}/..
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        CXXFLAGS: "-Wno-narrowing"
        CCACHE_DIR: ${{ runner.temp }}/ccache-solc
        CCACHE_BASEDIR: ${{ github.workspace }}
        CCACHE_NOHASHDIR: "true"
        CCACHE_COMPILERCHECK: "content"
      run: |
        set -x
        ./target/release/solx-dev solc build \
          --build-type ${{ inputs.cmake-build-type }} \
          --boost-version ${{ inputs.boost-version }} \
          --build-boost \
          --ccache-variant=ccache

    - name: Save Boost cache
      if: github.event_name != 'pull_request'
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ${{ inputs.working-dir }}/boost
        key: v1-boost-${{ inputs.boost-version }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('solx-dev/src/solc/boost.rs') }}

    - name: Show ccache stats
      if: always()
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        CCACHE_DIR: ${{ runner.temp }}/ccache-solc
      run: ccache --show-stats
