# The general action to build solc.
# It is universal for all platforms: Linux, macOS and Windows.
# Build logic is implemented in solx-dev Rust tool.

name: 'Build solc'
description: 'Builds solc executable.'
inputs:
  working-dir:
    description: 'Working directory containing solx-solidity submodule.'
    required: false
    default: 'solx-solidity'
  cmake-build-type:
    description: 'CMake build type (Release, Debug, or RelWithDebInfo).'
    required: false
    default: 'Release'
  boost-version:
    description: 'Boost version.'
    required: false
    default: '1.83.0'
  enable-mlir:
    description: 'Enable MLIR support.'
    required: false
    default: 'false'
  use-gcc:
    description: 'Use GCC compiler instead of clang (required for old versions <=0.4.16).'
    required: false
    default: 'false'
  upload-testing-binary:
    description: 'Upload build artifacts for testing.'
    required: false
    default: 'true'
  extra-args:
    description: 'Extra CMake arguments.'
    required: false
    default: ''
  # Legacy inputs for backwards compatibility (ignored)
  build-type:
    description: 'Deprecated: use cmake-build-type instead.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:

    # Note: Rust cache is provided by build-rust action.
    # Workflows should call build-rust before this action.

    - name: Build solx-dev
      # Run from the checkout root that owns solx-solidity
      working-directory: ${{ inputs.working-dir }}/..
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: |
        set -e
        TARGET_DIR="${CARGO_TARGET_DIR:-./target}"
        REV_FILE="${TARGET_DIR}/.solx-dev-revision"
        CURRENT_REV="$(git rev-parse HEAD 2>/dev/null || true)"
        if [ -x "${TARGET_DIR}/release/solx-dev" ] || [ -x "${TARGET_DIR}/release/solx-dev.exe" ]; then
          if [ -n "${CURRENT_REV}" ] && [ -f "${REV_FILE}" ] && [ "$(cat "${REV_FILE}")" = "${CURRENT_REV}" ]; then
            echo "solx-dev already built for ${CURRENT_REV}; skipping."
            exit 0
          fi
        fi
        cargo build --release --bin solx-dev
        if [ -n "${CURRENT_REV}" ]; then
          echo "${CURRENT_REV}" > "${REV_FILE}"
        fi

    - name: Cache Boost
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-dir }}/boost
        key: boost-${{ runner.os }}-${{ runner.arch }}-${{ inputs.boost-version }}

    - name: Build solc
      # Run from the checkout root that owns solx-solidity
      working-directory: ${{ inputs.working-dir }}/..
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        CXXFLAGS: "-Wno-narrowing"
      run: |
        set -x
        TARGET_DIR="${CARGO_TARGET_DIR:-./target}"
        [ "${{ inputs.enable-mlir }}" = "true" ] && ENABLE_MLIR="--enable-mlir"
        [ "${{ inputs.use-gcc }}" = "true" ] && USE_GCC="--use-gcc"
        [ "${{ inputs.extra-args }}" != "" ] && EXTRA_ARGS="--extra-args ${{ inputs.extra-args }}"

        "${TARGET_DIR}/release/solx-dev" solc build \
          --build-type ${{ inputs.cmake-build-type }} \
          --boost-version ${{ inputs.boost-version }} \
          --build-boost \
          ${ENABLE_MLIR} ${USE_GCC} ${EXTRA_ARGS}

    - name: Upload boost artifacts
      if: ${{ inputs.upload-testing-binary == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: boost-${{ runner.os }}-${{ runner.arch }}
        path: ${{ inputs.working-dir }}/boost

    - name: Upload build artifacts
      if: ${{ inputs.upload-testing-binary == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: build-solc-${{ runner.os }}-${{ runner.arch }}
        path: ${{ inputs.working-dir }}/build
