# The general action to build solc.
# It is universal for all platforms: Linux, macOS and Windows.
# Build logic is implemented in solx-dev Rust tool.

name: 'Build solc'
description: 'Builds solc executable.'
inputs:
  working-dir:
    description: 'Working directory containing solx-solidity submodule.'
    required: false
    default: 'solx-solidity'
  cmake-build-type:
    description: 'CMake build type (Release, Debug, or RelWithDebInfo).'
    required: false
    default: 'Release'
  boost-version:
    description: 'Boost version.'
    required: false
    default: '1.83.0'
  enable-mlir:
    description: 'Enable MLIR support.'
    required: false
    default: 'false'
  use-gcc:
    description: 'Use GCC compiler instead of clang (required for old versions <=0.4.16).'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:

    - name: Build solx-dev
      # Run from the checkout root that owns solx-solidity
      working-directory: ${{ inputs.working-dir }}/..
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cargo build --release --bin solx-dev

    - name: Build solc
      # Run from the checkout root that owns solx-solidity
      working-directory: ${{ inputs.working-dir }}/..
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        CXXFLAGS: "-Wno-narrowing"
      run: |
        set -x
        [ "${{ inputs.enable-mlir }}" = "true" ] && ENABLE_MLIR="--enable-mlir"
        [ "${{ inputs.use-gcc }}" = "true" ] && USE_GCC="--use-gcc"

        ./target/release/solx-dev solc build \
          --build-type ${{ inputs.cmake-build-type }} \
          --boost-version ${{ inputs.boost-version }} \
          --build-boost \
          ${ENABLE_MLIR} ${USE_GCC}
